language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "StreunerDeekman"
  - git config user.email "3112641066@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${7e287656f1b321cd381c779a7deb7381ef60647d}@${git@github.com:StreunerDeekman/Deekman.git}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: git@github.com:StreunerDeekman/Deekman.git